import cv2
import numpy as np

from cozmo_fsm import *

class SpiralScan(StateMachineProgram):
    def __init__(self):
        super().__init__(viewer_crosshairs=True, particle_viewer=True)
        self.patches = None
        self.iterVal = 0
        self.startDistance = 10
        self.deltaDistance = 10

    def start(self):
        super().start()
        robot.camera.color_image_enabled = True

    class GrabPatch(StateNode):
        def start(self,event=None):
            super().start(event)
            if isinstance(event, DataEvent):
                value = event.data
                self.parent.iterVal = value
            img = np.array(self.robot.world.latest_image.raw_image)
            self.parent.patch = img[115:125, 155:165, :]
            patch2 = cv2.cvtColor(self.parent.patch, cv2.COLOR_RGB2BGR)
            patch2 = np.expand_dims(patch2, 0)
            if value == 0:
                self.parent.patches = patch2
            else:
                self.parent.patches = np.append(self.parent.patches, patch2, axis=0)
            print(value, self.parent.patches.shape)
            self.post_completion()

    class SavePatches(StateNode):
        def start(self,event=None):
            super().start(event)
            with open('test.npy', 'wb') as f:
                np.save(f, self.parent.patches)
    
    class SpiralForward(Forward):
        def start(self, event=None):
            startDistance = self.parent.startDistance
            deltaDistance = self.parent.deltaDistance
            iterVal = self.parent.iterVal
            self.distance = distance_mm(startDistance + deltaDistance*(iterVal//2))
            print(iterVal, self.distance)
            super().start(event)

    def setup(self):
        """
            start: SetHeadAngle(-5) 
            start =C=> outer_loop
    
            outer_loop: Iterate(50)
            outer_loop =D=> grab =C=> move_spiral
            outer_loop =C=> save
    
            grab: self.GrabPatch()
            move_spiral: self.SpiralForward() =C=> Turn(90) =T(2)=> Say('Taking Patch') =CNext=> outer_loop
            save: self.SavePatches()
        """
        
        # Code generated by genfsm on Mon Apr 20 09:36:01 2020:
        
        start = SetHeadAngle(-5) .set_name("start") .set_parent(self)
        outer_loop = Iterate(50) .set_name("outer_loop") .set_parent(self)
        grab = self.GrabPatch() .set_name("grab") .set_parent(self)
        move_spiral = self.SpiralForward() .set_name("move_spiral") .set_parent(self)
        turn1 = Turn(90) .set_name("turn1") .set_parent(self)
        say1 = Say('Taking Patch') .set_name("say1") .set_parent(self)
        save = self.SavePatches() .set_name("save") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(outer_loop)
        
        datatrans1 = DataTrans() .set_name("datatrans1")
        datatrans1 .add_sources(outer_loop) .add_destinations(grab)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(grab) .add_destinations(move_spiral)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(outer_loop) .add_destinations(save)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(move_spiral) .add_destinations(turn1)
        
        timertrans1 = TimerTrans(2) .set_name("timertrans1")
        timertrans1 .add_sources(turn1) .add_destinations(say1)
        
        cnexttrans1 = CNextTrans() .set_name("cnexttrans1")
        cnexttrans1 .add_sources(say1) .add_destinations(outer_loop)
        
        return self
